"""Hikvision log event codes: (major, minor) -> (name, description).

The numbers and names are Hikvision's own, as published in the device
network SDK header (HCNetSDK.h: MAJOR_* / MINOR_* constants and their
comments).  They name what a record on the disk says happened; they are
data, not a decoding of ours.  A code missing here is reported as
undefined - newer firmware logs codes this SDK version does not list.
"""

MAJOR = {1: "Alarm", 2: "Exception", 3: "Operation", 4: "Information"}

MINOR = {
    (1, 0x01): ('ALARM_IN', 'Alarm input'),
    (1, 0x02): ('ALARM_OUT', 'Alarm output'),
    (1, 0x03): ('MOTDET_START', 'Motion detection alarm start'),
    (1, 0x04): ('MOTDET_STOP', 'Motion detection alarm stop'),
    (1, 0x05): ('HIDE_ALARM_START', 'Mask alarm start'),
    (1, 0x06): ('HIDE_ALARM_STOP', 'Mask alarm stop'),
    (1, 0x07): ('VCA_ALARM_START', 'VCA alarm start'),
    (1, 0x08): ('VCA_ALARM_STOP', 'VCA alarm stop'),
    (1, 0x09): ('ITS_ALARM_START', 'Traffic event alarm start'),
    (1, 0x0A): ('ITS_ALARM_STOP', 'Traffic event alarm stop'),
    (1, 0x0B): ('NETALARM_START', 'Net alarm start'),
    (1, 0x0C): ('NETALARM_STOP', 'Net alarm stop'),
    (1, 0x0E): ('WIRELESS_ALARM_START', 'wireless alarm start'),
    (1, 0x0F): ('WIRELESS_ALARM_STOP', 'wireless alarm stop'),
    (1, 0x10): ('PIR_ALARM_START', 'PIR alarm start'),
    (1, 0x11): ('PIR_ALARM_STOP', 'PIR alarm stop'),
    (1, 0x12): ('CALLHELP_ALARM_START', 'callhelp start'),
    (1, 0x13): ('CALLHELP_ALARM_STOP', 'callhelp stop'),
    (1, 0x14): ('IPCHANNEL_ALARMIN_START', 'IP channel alarm in start'),
    (1, 0x15): ('IPCHANNEL_ALARMIN_STOP', 'IP channel alarm in stop.'),
    (2, 0x20): ('RAID_ERROR', 'RAID Exception'),
    (2, 0x21): ('VI_LOST', 'Video loss'),
    (2, 0x22): ('ILLEGAL_ACCESS', 'Illegal access'),
    (2, 0x23): ('HD_FULL', 'HD full'),
    (2, 0x24): ('HD_ERROR', 'HD error'),
    (2, 0x25): ('DCD_LOST', 'MODEM off- line (Reserved)'),
    (2, 0x26): ('IP_CONFLICT', 'IP conflict'),
    (2, 0x27): ('NET_BROKEN', 'Network disconnected'),
    (2, 0x28): ('REC_ERROR', 'Record error'),
    (2, 0x29): ('IPC_NO_LINK', 'IPC connection failed'),
    (2, 0x2A): ('VI_EXCEPTION', 'Video input error (for analog channel only)'),
    (2, 0x2B): ('IPC_IP_CONFLICT', 'IPC IP conflict'),
    (2, 0x2C): ('SENCE_EXCEPTION', 'Sence exception'),
    (2, 0x2D): ('PIC_REC_ERROR', 'Snapshot error!'),
    (2, 0x2E): ('VI_MISMATCH', 'Video format error.'),
    (2, 0x2F): ('RESOLUTION_MISMATCH', 'Resolution miamatch'),
    (2, 0x31): ('FANABNORMAL', 'Video integrated platform'),
    (2, 0x32): ('FANRESUME', 'Video integrated platform'),
    (2, 0x33): ('SUBSYSTEM_ABNORMALREBOOT', 'Video integrated platform'),
    (2, 0x34): ('MATRIX_STARTBUZZER', 'Video integrated platform'),
    (2, 0x35): ('NET_ABNORMAL', 'Net abnormal'),
    (2, 0x36): ('MEM_ABNORMAL', 'Memory abnormal'),
    (2, 0x37): ('FILE_ABNORMAL', 'File abnormal'),
    (3, 0x3C): ('SCREEN_SUBSYSTEM_ABNORMALREBOOT', 'abnormal reboot'),
    (3, 0x3D): ('SCREEN_SUBSYSTEM_ABNORMALINSERT', 'sub board insert'),
    (3, 0x3E): ('SCREEN_SUBSYSTEM_ABNORMALPULLOUT', 'sub board pull out'),
    (3, 0x3F): ('SCREEN_ABNARMALTEMPERATURE', 'abnormal temperature'),
    (3, 0x40): ('HIGH_TEMPERATURE_PROTECT', 'sub board high temperature protect'),
    (3, 0x41): ('START_DVR', 'Power On'),
    (3, 0x42): ('STOP_DVR', 'Power off'),
    (3, 0x43): ('STOP_ABNORMAL', 'Illegal shut down'),
    (3, 0x44): ('REBOOT_DVR', 'Local reboot DVR'),
    (3, 0x50): ('LOCAL_LOGIN', 'Login (local)'),
    (3, 0x51): ('LOCAL_LOGOUT', 'Logout (local)'),
    (3, 0x52): ('LOCAL_CFG_PARM', 'Configuration (local)'),
    (3, 0x53): ('LOCAL_PLAYBYFILE', 'Playback (local)'),
    (3, 0x54): ('LOCAL_PLAYBYTIME', 'Playback or download by time (local)'),
    (3, 0x55): ('LOCAL_START_REC', 'Start record (local)'),
    (3, 0x56): ('LOCAL_STOP_REC', 'Stop record (local)'),
    (3, 0x57): ('LOCAL_PTZCTRL', 'PTZ control (local)'),
    (3, 0x58): ('LOCAL_PREVIEW', 'Preview (local) (Reserved)'),
    (3, 0x59): ('LOCAL_MODIFY_TIME', 'Change time (local) (Reserved)'),
    (3, 0x5A): ('LOCAL_UPGRADE', 'Upgrade (local)'),
    (3, 0x5B): ('LOCAL_RECFILE_OUTPUT', 'Backup (local)'),
    (3, 0x5C): ('LOCAL_FORMAT_HDD', 'HD format (local)'),
    (3, 0x5D): ('LOCAL_CFGFILE_OUTPUT', 'Export Configuration (local)'),
    (3, 0x5E): ('LOCAL_CFGFILE_INPUT', 'Import Configuration (local)'),
    (3, 0x5F): ('LOCAL_COPYFILE', 'Backup file (local)'),
    (3, 0x60): ('LOCAL_LOCKFILE', 'File lockup (local) Reboot IPC (local)'),
    (3, 0x61): ('LOCAL_UNLOCKFILE', 'File unlock (local)'),
    (3, 0x62): ('LOCAL_DVR_ALARM', 'Clear/Trigger Alarm (Local)'),
    (3, 0x63): ('IPC_ADD', 'Add IPC (local)'),
    (3, 0x64): ('IPC_DEL', 'Delete IPC (local)'),
    (3, 0x65): ('IPC_SET', 'Set IPC (local)'),
    (3, 0x66): ('LOCAL_START_BACKUP', 'local start backup file'),
    (3, 0x67): ('LOCAL_STOP_BACKUP', 'local stop backup file'),
    (3, 0x68): ('LOCAL_COPYFILE_START_TIME', 'local backup'),
    (3, 0x69): ('LOCAL_COPYFILE_END_TIME', 'local backup'),
    (3, 0x6A): ('LOCAL_ADD_NAS', 'Add network hard disk in local configuration (NFS/iSCSI)'),
    (3, 0x6B): ('LOCAL_DEL_NAS', 'Delete network hard disk in local configuration (NFS/iSCSI)'),
    (3, 0x6C): ('LOCAL_SET_NAS', 'Set network hard disk in local configuration (NFS/iSCSI)'),
    (3, 0x6D): ('LOCAL_RESET_PASSWD', "Local Resume Admin's Password"),
    (3, 0x70): ('REMOTE_LOGIN', 'Login (remote)'),
    (3, 0x71): ('REMOTE_LOGOUT', 'Logout (remote)'),
    (3, 0x72): ('REMOTE_START_REC', 'Start record (remote)'),
    (3, 0x73): ('REMOTE_STOP_REC', 'Stop record (remote)'),
    (3, 0x74): ('START_TRANS_CHAN', 'Start transparent channel (remote)'),
    (3, 0x75): ('STOP_TRANS_CHAN', 'Stop transparent channel (remote)'),
    (3, 0x76): ('REMOTE_GET_PARM', 'Get parameter (remote)'),
    (3, 0x77): ('REMOTE_CFG_PARM', 'configuration (remote)'),
    (3, 0x78): ('REMOTE_GET_STATUS', 'Get status (remote)'),
    (3, 0x79): ('REMOTE_ARM', 'On guard (remote)'),
    (3, 0x7A): ('REMOTE_DISARM', 'Disarm (remote)'),
    (3, 0x7B): ('REMOTE_REBOOT', 'Reboot (remote)'),
    (3, 0x7C): ('START_VT', 'Start voice talk'),
    (3, 0x7D): ('STOP_VT', 'Stop voice talk'),
    (3, 0x7E): ('REMOTE_UPGRADE', 'upgrade (remote)'),
    (3, 0x7F): ('REMOTE_PLAYBYFILE', 'Playback by file name (remote)'),
    (3, 0x80): ('REMOTE_PLAYBYTIME', 'Playback by time (remote)'),
    (3, 0x81): ('REMOTE_PTZCTRL', 'PTZ control (remote)'),
    (3, 0x82): ('REMOTE_FORMAT_HDD', 'Format hard disk (remote)'),
    (3, 0x83): ('REMOTE_STOP', 'Shut Down (remote)'),
    (3, 0x84): ('REMOTE_LOCKFILE', 'File lockup (remote)'),
    (3, 0x85): ('REMOTE_UNLOCKFILE', 'File unlock (remote'),
    (3, 0x86): ('REMOTE_CFGFILE_OUTPUT', 'Export Configuration (remote)'),
    (3, 0x87): ('REMOTE_CFGFILE_INTPUT', 'Import Configuration (remote)'),
    (3, 0x88): ('REMOTE_RECFILE_OUTPUT', 'Backup recording files (remote)'),
    (3, 0x89): ('REMOTE_DVR_ALARM', 'Trigger/clear alarm (remote)'),
    (3, 0x8A): ('REMOTE_IPC_ADD', 'Add IPC (remote)'),
    (3, 0x8B): ('REMOTE_IPC_DEL', 'Delete IPC (remote)'),
    (3, 0x8C): ('REMOTE_IPC_SET', 'Set IPC (remote)'),
    (3, 0x8D): ('REBOOT_VCA_LIB', 'Reboot vca library'),
    (3, 0x8E): ('REMOTE_ADD_NAS', 'Remote add nas disk'),
    (3, 0x8F): ('REMOTE_DEL_NAS', 'Remote delete nas disk'),
    (3, 0x90): ('REMOTE_SET_NAS', 'Remote set nas disk'),
    (3, 0x91): ('LOCAL_START_REC_CDRW', 'Local start CD/DVD writing'),
    (3, 0x92): ('LOCAL_STOP_REC_CDRW', 'Local stop CD/DVD writing'),
    (3, 0x93): ('REMOTE_START_REC_CDRW', 'Remote Start CD/DVD writing'),
    (3, 0x94): ('REMOTE_STOP_REC_CDRW', 'Remote stop CD/DVD writing'),
    (3, 0x95): ('LOCAL_PIC_OUTPUT', 'local save picture'),
    (3, 0x96): ('REMOTE_PIC_OUTPUT', 'remote save picture'),
    (3, 0x97): ('LOCAL_INQUEST_RESUME', 'local resume inquest event'),
    (3, 0x98): ('REMOTE_INQUEST_RESUME', 'remote resume inquest event'),
    (3, 0xA0): ('SUBSYSTEMREBOOT', 'Video integrated platform'),
    (3, 0xA1): ('MATRIX_STARTTRANSFERVIDEO', 'Video integrated platform'),
    (3, 0xA2): ('MATRIX_STOPTRANSFERVIDEO', 'Video integrated platform'),
    (3, 0xA3): ('REMOTE_SET_ALLSUBSYSTEM', 'Video integrated platform'),
    (3, 0xA4): ('REMOTE_GET_ALLSUBSYSTEM', 'Video integrated platform'),
    (3, 0xA5): ('REMOTE_SET_PLANARRAY', 'Video integrated platform'),
    (3, 0xA6): ('REMOTE_GET_PLANARRAY', 'Video integrated platform'),
    (3, 0xA7): ('MATRIX_STARTTRANSFERAUDIO', 'Video integrated platform'),
    (3, 0xA8): ('MATRIX_STOPRANSFERAUDIO', 'Video integrated platform'),
    (3, 0xA9): ('LOGON_CODESPITTER', 'Video integrated platform'),
    (3, 0xAA): ('LOGOFF_CODESPITTER', 'Video integrated platform'),
    (3, 0xB0): ('START_DYNAMIC_DECODE', 'Start dynamic decode'),
    (3, 0xB1): ('STOP_DYNAMIC_DECODE', 'Stop dynamic decode'),
    (3, 0xB2): ('GET_CYC_CFG', 'Get cycle config'),
    (3, 0xB3): ('SET_CYC_CFG', 'Set cycle config'),
    (3, 0xB4): ('START_CYC_DECODE', 'Start cycle decode'),
    (3, 0xB5): ('STOP_CYC_DECODE', 'Stop cycle decode'),
    (3, 0xB6): ('GET_DECCHAN_STATUS', 'Get decode channel status'),
    (3, 0xB7): ('GET_DECCHAN_INFO', 'Get decode channel information'),
    (3, 0xB8): ('START_PASSIVE_DEC', 'Start passive'),
    (3, 0xB9): ('STOP_PASSIVE_DEC', 'Stop passive decode'),
    (3, 0xBA): ('CTRL_PASSIVE_DEC', 'Passive decode control'),
    (3, 0xBB): ('RECON_PASSIVE_DEC', 'Passive decode reconnect'),
    (3, 0xBC): ('GET_DEC_CHAN_SW', 'Get decode channel switch'),
    (3, 0xBD): ('SET_DEC_CHAN_SW', 'Set decode channel switch'),
    (3, 0xBE): ('CTRL_DEC_CHAN_SCALE', 'Decode channel scale control'),
    (3, 0xBF): ('SET_REMOTE_REPLAY', 'Set remote replay'),
    (3, 0xC0): ('GET_REMOTE_REPLAY', 'Get remote replay'),
    (3, 0xC1): ('CTRL_REMOTE_REPLAY', 'Remote replay control'),
    (3, 0xC2): ('SET_DISP_CFG', 'Set display config'),
    (3, 0xC3): ('GET_DISP_CFG', 'Get display config'),
    (3, 0xC4): ('SET_PLANTABLE', 'Set plan table'),
    (3, 0xC5): ('GET_PLANTABLE', 'Get plan table'),
    (3, 0xC6): ('START_PPPPOE', 'Start pppoe'),
    (3, 0xC7): ('STOP_PPPPOE', 'Stop pppoe'),
    (3, 0xC8): ('UPLOAD_LOGO', 'Upload logo'),
    (3, 0x101): ('LOCAL_CONF_REB_RAID', 'Rebuild configuration automatically and locally'),
    (3, 0x102): ('LOCAL_CONF_SPARE', 'Hot spare of local configuration'),
    (3, 0x103): ('LOCAL_ADD_RAID', 'Add RAID locally'),
    (3, 0x104): ('LOCAL_DEL_RAID', 'Delete RAID locally'),
    (3, 0x105): ('LOCAL_MIG_RAID', 'Migrate RAID locally'),
    (3, 0x106): ('LOCAL_REB_RAID', 'Rebuild RAID manually and locally'),
    (3, 0x107): ('LOCAL_QUICK_CONF_RAID', 'Quick local configuration by one key'),
    (3, 0x108): ('LOCAL_ADD_VD', 'Add visual disk locally'),
    (3, 0x109): ('LOCAL_DEL_VD', 'Delete visual disk locally'),
    (3, 0x10A): ('LOCAL_RP_VD', 'Repair visual disk locally'),
    (3, 0x10D): ('LOCAL_STOP_RAID', 'Local stop RAID'),
    (3, 0x111): ('REMOTE_CONF_REB_RAID', 'Rebuild configuration automatically and remotely'),
    (3, 0x112): ('REMOTE_CONF_SPARE', 'Hot spare of remote configuration'),
    (3, 0x113): ('REMOTE_ADD_RAID', 'Add RAID remotely'),
    (3, 0x114): ('REMOTE_DEL_RAID', 'Delete RAID remotely'),
    (3, 0x115): ('REMOTE_MIG_RAID', 'Migrate RAID remotely'),
    (3, 0x116): ('REMOTE_REB_RAID', 'Rebuild RAID manually and remotely'),
    (3, 0x117): ('REMOTE_QUICK_CONF_RAID', 'Quick remote configuration by one key'),
    (3, 0x118): ('REMOTE_ADD_VD', 'Add visual disk remotely'),
    (3, 0x119): ('REMOTE_DEL_VD', 'Delete visual disk remotely'),
    (3, 0x11A): ('REMOTE_RP_VD', 'Repair visual disk remotely'),
    (3, 0x11D): ('REMOTE_STOP_RAID', 'Remote stop RAID'),
    (3, 0x121): ('LOCAL_START_PIC_REC', 'local start snapshot'),
    (3, 0x122): ('LOCAL_STOP_PIC_REC', 'local stop snapshot'),
    (3, 0x125): ('LOCAL_SET_SNMP', 'local set SNMP'),
    (3, 0x126): ('LOCAL_TAG_OPT', 'local operate label'),
    (3, 0x131): ('REMOTE_START_PIC_REC', 'remote start snapshot'),
    (3, 0x132): ('REMOTE_STOP_PIC_REC', 'remote stop snapshot'),
    (3, 0x135): ('REMOTE_SET_SNMP', 'remote set SNMP'),
    (3, 0x136): ('REMOTE_TAG_OPT', 'remote operate label'),
    (3, 0x140): ('LOCAL_VOUT_SWITCH', 'local video out switch'),
    (3, 0x141): ('STREAM_CABAC', 'stream cabac configuration'),
    (3, 0x201): ('SET_MULTI_MASTER', 'set multi master'),
    (3, 0x202): ('SET_MULTI_SLAVE', 'set multi slave'),
    (3, 0x203): ('CANCEL_MULTI_MASTER', 'cancel multi master'),
    (3, 0x204): ('CANCEL_MULTI_SLAVE', 'cancel multi slave'),
    (3, 0x251): ('SCREEN_SET_INPUT', 'set input signal'),
    (3, 0x252): ('SCREEN_SET_OUTPUT', 'set output channel'),
    (3, 0x253): ('SCREEN_SET_OSD', 'set OSD'),
    (3, 0x254): ('SCREEN_SET_LOGO', 'set LOGO'),
    (3, 0x255): ('SCREEN_SET_LAYOUT', 'set layout'),
    (3, 0x256): ('SCREEN_PICTUREPREVIEW', 'picture preview'),
    (3, 0x257): ('SCREEN_GET_OSD', 'get OSD'),
    (3, 0x258): ('SCREEN_GET_LAYOUT', 'get layout'),
    (3, 0x259): ('SCREEN_LAYOUT_CTRL', 'layout control'),
    (3, 0x260): ('GET_ALL_VALID_WND', 'get all valid window'),
    (3, 0x261): ('GET_SIGNAL_WND', 'get single window information'),
    (3, 0x262): ('WINDOW_CTRL', 'window control'),
    (3, 0x263): ('GET_LAYOUT_LIST', 'get layout list'),
    (3, 0x264): ('LAYOUT_CTRL', 'layout control'),
    (3, 0x265): ('SET_LAYOUT', 'set single layout'),
    (3, 0x266): ('GET_SIGNAL_LIST', 'get input signal list'),
    (3, 0x267): ('GET_PLAN_LIST', 'get plan list'),
    (3, 0x268): ('SET_PLAN', 'set plan'),
    (3, 0x269): ('CTRL_PLAN', 'plan control'),
    (3, 0x270): ('CTRL_SCREEN', 'screen control'),
    (3, 0x271): ('ADD_NETSIG', 'add net signal'),
    (3, 0x272): ('SET_NETSIG', 'mod net signal'),
    (3, 0x273): ('SET_DECBDCFG', 'set decoder parameter'),
    (3, 0x274): ('GET_DECBDCFG', 'get decoder parameter'),
    (3, 0x275): ('GET_DEVICE_STATUS', 'get device status'),
    (3, 0x276): ('UPLOAD_PICTURE', 'upload picture'),
    (3, 0x277): ('SET_USERPWD', 'set user name and password'),
    (3, 0x278): ('ADD_LAYOUT', 'add layout'),
    (3, 0x279): ('DEL_LAYOUT', 'delete layout'),
    (3, 0x280): ('DEL_NETSIG', 'delete net signal'),
    (3, 0x281): ('ADD_PLAN', 'add plan'),
    (3, 0x282): ('DEL_PLAN', 'delete plan'),
    (3, 0x1001): ('SET_TRIGGERMODE_CFG', 'Set trigger configuration'),
    (3, 0x1002): ('GET_TRIGGERMODE_CFG', 'Get trigger configuration'),
    (3, 0x1003): ('SET_IOOUT_CFG', 'Set IO out configuration'),
    (3, 0x1004): ('GET_IOOUT_CFG', 'Get IO out configuration'),
    (3, 0x1005): ('GET_TRIGGERMODE_DEFAULT', 'Get trigger default configuration'),
    (3, 0x1006): ('GET_ITCSTATUS', 'Get status'),
    (3, 0x1007): ('SET_STATUS_DETECT_CFG', 'Set status detect configuration'),
    (3, 0x1008): ('GET_STATUS_DETECT_CFG', 'Get status detect configuration'),
    (3, 0x1009): ('SET_VIDEO_TRIGGERMODE_CFG', 'Set video trigger configuration'),
    (3, 0x100A): ('GET_VIDEO_TRIGGERMODE_CFG', 'Get video trigger configuration'),
    (4, 0xA1): ('HDD_INFO', 'HD info'),
    (4, 0xA2): ('SMART_INFO', 'SMART info'),
    (4, 0xA3): ('REC_START', 'Start record'),
    (4, 0xA4): ('REC_STOP', 'Stop record'),
    (4, 0xA5): ('REC_OVERDUE', 'Record overdue'),
    (4, 0xA6): ('LINK_START', 'start to link device'),
    (4, 0xA7): ('LINK_STOP', 'stop to link device'),
    (4, 0xA8): ('NET_DISK_INFO', 'Network hard disk info'),
    (4, 0xA9): ('RAID_INFO', 'raid Info'),
    (4, 0xB3): ('PIC_REC_START', 'start snapshot'),
    (4, 0xB4): ('PIC_REC_STOP', 'stop snapshot'),
    (4, 0xB5): ('PIC_REC_OVERDUE', 'delete delayed picture'),
}
